### ISSUE TITLE
Save files disappearing

### ISSUE THREAD

**Issue by nwarford** [juandesant/spatterlight#5]
When I use the save command in-game, no save file is created (and thus, the restore command is useless).

**Comment by angstsmurf** [comment]
Was this with the new version that I just uploaded? That was the major bug it was supposed to fix.

With previous versions, your save files will probably end up in your home directory. Sorry about this!

**Comment by angstsmurf** [comment]
Sorry, I though that this bug report was on my fork. My new version is here: https://github.com/angstsmurf/spatterlight/releases

**Comment by nwarford** [comment]
As it happens, I just happened to download Spatterlight earlier today (version 0.5.7b), so I just had the bad luck of trying too early! I found my save files - fortunately, none of them were too far gone that it particularly matters.

**Comment by angstsmurf** [comment]
Good to hear!

I just noticed that issues reporting was disabled for some reason on the Github page of my fork, so now I have enabled it. You are welcome to report anything else you find or would like to see implemented [there](https://github.com/angstsmurf/spatterlight/issues)!
